const ip = "http://localhost:8080/"
export const matchesUrl = ip + "api/matches/";
export const teamsUrl = ip + "api/teams/";
export const clubUrl = ip + "api/clubs/"
export const refereeUrl = ip + "api/users/referee/";
export const refereeUrlChangePassword = ip + "api/users/refereePassword";
export let makeAdminUrl = ip + "api/users/makeAdmin/"
export const refereesUrl = ip + "api/users/referees";
export const loginUrl = ip + "api/auth/login";
export const signupsUrl = ip + "api/signups/findSignups/";
export const addSignUpUrl = ip + "api/signups";
export const myMatchesUrl = ip + "api/users/matches/";